services:
  # --- IL DATABASE (MongoDB) ---
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db # Sdove salvo i dati del DB
    networks:
      - flights-network

  # --- IL BACKEND (Node.js) ---
  server:
    build: ./server
    container_name: taw-server
    ports:
      - "3005:3000"
    command: node server.js
    depends_on:
      - mongo # Aspetta che il DB sia pronto
    environment:
      # Questa stringa è magica: 'mongo' è il nome del servizio sopra
      - MONGO_URL=mongodb://mongo:27017/db_flightdb
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - flights-network

  # --- IL FRONTEND (Angular) ---
  angular:
      build: ./frontend
      container_name: taw-angular
      ports:
        - "4200:4200"
      volumes:
        - ./frontend:/app       # Sincronizza la cartella mentre modifichi il codice
        - /app/node_modules     # REGOLA D'ORO: Usa i node_modules del container, non del PC
      networks:
        - flights-network


networks:
  flights-network:
